# Generated by Django 4.2.7 on 2025-12-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codefeedback',
            name='correctness_score',
        ),
        migrations.RemoveField(
            model_name='codefeedback',
            name='efficiency_score',
        ),
        migrations.RemoveField(
            model_name='codefeedback',
            name='quality_score',
        ),
        migrations.RemoveField(
            model_name='codefeedback',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='codefeedback',
            name='interview_ready_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codefeedback',
            name='scores',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='interview_ready_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='scores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='time_taken_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codefeedback',
            name='feedback',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='feedback',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
