# Generated by Django 6.0 on 2025-12-09 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_problem_options_problem_constraints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_format',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_format',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution_outline',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('hidden', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='problems.problem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
