# Generated by Django 5.2.8 on 2025-12-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_attempt_status_attempt_updated_at_aireview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
