# Generated by Django 6.0 on 2025-12-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair_program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairsession',
            name='session_code',
            field=models.CharField(default='Default', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
