# Generated by Django 6.0 on 2025-12-16 16:52

import pair_program.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair_program', '0002_pairsession_session_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairsession',
            name='problem_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pairsession',
            name='session_code',
            field=models.CharField(default=pair_program.models.generate_session_code, max_length=12, unique=True),
        ),
    ]
